# Generated by Django 4.0.4 on 2022-07-22 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_what_you_learn_requirements'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='requirements',
            options={'verbose_name_plural': 'Requirements'},
        ),
        migrations.AlterModelOptions(
            name='what_you_learn',
            options={'verbose_name_plural': 'What_you_learn'},
        ),
    ]
