# Generated by Django 4.0.4 on 2022-07-22 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_requirements_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categories',
            options={'verbose_name_plural': 'Categories'},
        ),
    ]
